// Code generated by mockery v1.0.0. DO NOT EDIT.

package warta

import mock "github.com/stretchr/testify/mock"

// mockListener is an autogenerated mock type for the listener type
type mockListener struct {
	mock.Mock
}

// Callback provides a mock function with given fields:
func (_m *mockListener) Callback() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *mockListener) Close() {
	_m.Called()
}

// getID provides a mock function with given fields:
func (_m *mockListener) getID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
